//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionInfo
    {
        public int AdmId { get; set; }
        public Nullable<int> StdtId { get; set; }
        public Nullable<int> FeeCommitmentId { get; set; }
        public string AdmissionNumber { get; set; }
        public System.DateTime AdmDate { get; set; }
        public string Section { get; set; }
        public string AdmType { get; set; }
        public string IsActive { get; set; }
        public string TransportRequired { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual StudentInfo StudentInfo { get; set; }
        public virtual SchoolFeeCommitment SchoolFeeCommitment { get; set; }
    }
}
