//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildActivity
    {
        public int AdmNo { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string ActivityText { get; set; }
        public string NoticeText { get; set; }
        public string HomeWorkText { get; set; }
        public string PictureId { get; set; }
    }
}
