//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerQuery
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string QueryResponse { get; set; }
        public Nullable<System.DateTime> QueryResponseDate { get; set; }
        public string IsQueryResponded { get; set; }
    }
}
