//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAttendanceRegister
    {
        public int AttandanceId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> AttendanceInDate { get; set; }
        public Nullable<System.DateTime> AttendanceOutDate { get; set; }
    }
}
