//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpAddress { get; set; }
        public string EmpEducation { get; set; }
        public string LastEmployment { get; set; }
        public string LastEmploymentReasonForLeaving { get; set; }
        public string EmpCode { get; set; }
        public string IsActive { get; set; }
        public string UserId { get; set; }
        public byte[] EmpPhotoPath { get; set; }
        public string MobileNo { get; set; }
        public string AlternateNo { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Email { get; set; }
    }
}
