//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeDeposit
    {
        public int FeeDepositId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public double AmountDeposited { get; set; }
        public string Mode { get; set; }
        public string ChequeNumber { get; set; }
        public string Month { get; set; }
        public string FeeCategory { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UPdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
