//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolNotice
    {
        public int NoticeId { get; set; }
        public string NoticeText { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
    }
}
