//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolFeeCommitment
    {
        public SchoolFeeCommitment()
        {
            this.AdmissionInfoes = new HashSet<AdmissionInfo>();
        }
    
        public int FeeId { get; set; }
        public double MonthlyFee { get; set; }
        public double FormFee { get; set; }
        public double AnnualFee { get; set; }
        public double AdmFee { get; set; }
        public double KitCharge { get; set; }
        public double DayCareFee { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UPdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<AdmissionInfo> AdmissionInfoes { get; set; }
    }
}
