//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmarteezDatabaseEntities : DbContext
    {
        public SmarteezDatabaseEntities()
            : base("name=SmarteezDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmissionInfo> AdmissionInfoes { get; set; }
        public virtual DbSet<ChildActivity> ChildActivities { get; set; }
        public virtual DbSet<CustomerQuery> CustomerQueries { get; set; }
        public virtual DbSet<EmpAttendanceRegister> EmpAttendanceRegisters { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FeeDeposit> FeeDeposits { get; set; }
        public virtual DbSet<SchoolFeeCommitment> SchoolFeeCommitments { get; set; }
        public virtual DbSet<SchoolNotice> SchoolNotices { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WebSiteUser> WebSiteUsers { get; set; }
    }
}
