//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public StudentInfo()
        {
            this.AdmissionInfoes = new HashSet<AdmissionInfo>();
            this.FeeDeposits = new HashSet<FeeDeposit>();
        }
    
        public int StudentId { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Nationality { get; set; }
        public string Addrerss { get; set; }
        public decimal EmergencyContactNo { get; set; }
        public string NameOfPersonToBeContacted { get; set; }
        public string RelationShip { get; set; }
        public string PreviousSchoolAttended { get; set; }
        public string ReasonForLeaving { get; set; }
        public string FatherName { get; set; }
        public string FatherQualification { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherOrgWorkFor { get; set; }
        public string FatherDesignation { get; set; }
        public decimal FatherPhone { get; set; }
        public string FatherEmailId { get; set; }
        public string MotherName { get; set; }
        public string MotherQualification { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherOrgWorkingFor { get; set; }
        public string MotherDesignation { get; set; }
        public decimal MotherPhone { get; set; }
        public string MotherEmailId { get; set; }
        public string MedicalHistOfChild { get; set; }
        public byte[] ChildPhoto { get; set; }
        public string UserLogin { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<AdmissionInfo> AdmissionInfoes { get; set; }
        public virtual ICollection<FeeDeposit> FeeDeposits { get; set; }
    }
}
