//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSiteUser
    {
        public int Id { get; set; }
        public string MachineIP { get; set; }
        public string ClientBrowser { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
    }
}
